source 'https://rubygems.org'

# Test against branch with removed settings
gem 'spree', path: "../extensions/spree"

# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-3-stable'

gemspec
