class AddSizeAttributesToProduct < ActiveRecord::Migration
  def change
    add_column :spree_products, :material, :text
    add_column :spree_products, :remarks,  :text
    add_column :spree_products, :model,    :text
    add_column :spree_products, :xs_1,     :string
    add_column :spree_products, :xs_2,     :string
    add_column :spree_products, :xs_3,     :string
    add_column :spree_products, :xs_4,     :string
    add_column :spree_products, :xs_5,     :string 
    add_column :spree_products, :xs_6,     :string
    add_column :spree_products, :xs_7,     :string
    add_column :spree_products, :xs_8,     :string
    add_column :spree_products, :xs_9,     :string
    add_column :spree_products, :xs_10,    :string
    add_column :spree_products, :xs_11,    :string
    add_column :spree_products, :xs_12,    :string
    add_column :spree_products, :xs_13,    :string
    add_column :spree_products, :xs_14,    :string
    add_column :spree_products, :xs_15,    :string
    add_column :spree_products, :s_1,      :string
    add_column :spree_products, :s_2,      :string
    add_column :spree_products, :s_3,      :string
    add_column :spree_products, :s_4,      :string
    add_column :spree_products, :s_5,      :string
    add_column :spree_products, :s_6,      :string
    add_column :spree_products, :s_7,      :string
    add_column :spree_products, :s_8,      :string
    add_column :spree_products, :s_9,      :string
    add_column :spree_products, :s_10,     :string
    add_column :spree_products, :s_11,     :string
    add_column :spree_products, :s_12,     :string
    add_column :spree_products, :s_13,     :string
    add_column :spree_products, :s_14,     :string
    add_column :spree_products, :s_15,     :string
    add_column :spree_products, :m_1,      :string
    add_column :spree_products, :m_2,      :string
    add_column :spree_products, :m_3,      :string
    add_column :spree_products, :m_4,      :string
    add_column :spree_products, :m_5,      :string
    add_column :spree_products, :m_6,      :string
    add_column :spree_products, :m_7,      :string
    add_column :spree_products, :m_8,      :string
    add_column :spree_products, :m_9,      :string
    add_column :spree_products, :m_10,     :string
    add_column :spree_products, :m_11,     :string
    add_column :spree_products, :m_12,     :string
    add_column :spree_products, :m_13,     :string
    add_column :spree_products, :m_14,     :string
    add_column :spree_products, :m_15,     :string
    add_column :spree_products, :l_1,      :string
    add_column :spree_products, :l_2,      :string
    add_column :spree_products, :l_3,      :string
    add_column :spree_products, :l_4,      :string
    add_column :spree_products, :l_5,      :string
    add_column :spree_products, :l_6,      :string
    add_column :spree_products, :l_7,      :string
    add_column :spree_products, :l_8,      :string
    add_column :spree_products, :l_9,      :string
    add_column :spree_products, :l_10,     :string
    add_column :spree_products, :l_11,     :string
    add_column :spree_products, :l_12,     :string
    add_column :spree_products, :l_13,     :string
    add_column :spree_products, :l_14,     :string
    add_column :spree_products, :l_15,     :string
    add_column :spree_products, :xl_1,     :string
    add_column :spree_products, :xl_2,     :string
    add_column :spree_products, :xl_3,     :string
    add_column :spree_products, :xl_4,     :string
    add_column :spree_products, :xl_5,     :string 
    add_column :spree_products, :xl_6,     :string
    add_column :spree_products, :xl_7,     :string
    add_column :spree_products, :xl_8,     :string
    add_column :spree_products, :xl_9,     :string
    add_column :spree_products, :xl_10,    :string
    add_column :spree_products, :xl_11,    :string
    add_column :spree_products, :xl_12,    :string
    add_column :spree_products, :xl_13,    :string
    add_column :spree_products, :xl_14,    :string
    add_column :spree_products, :xl_15,    :string
    add_column :spree_products, :f_1,      :string
    add_column :spree_products, :f_2,      :string
    add_column :spree_products, :f_3,      :string
    add_column :spree_products, :f_4,      :string
    add_column :spree_products, :f_5,      :string
    add_column :spree_products, :f_6,      :string
    add_column :spree_products, :f_7,      :string
    add_column :spree_products, :f_8,      :string
    add_column :spree_products, :f_9,      :string
    add_column :spree_products, :f_10,     :string
    add_column :spree_products, :f_11,     :string
    add_column :spree_products, :f_12,     :string
    add_column :spree_products, :f_13,     :string
    add_column :spree_products, :f_14,     :string
    add_column :spree_products, :f_15,     :string
  end
end
